---
title: "paper_figures"
author: "Megan Hasoon"
date: "2024-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(ggvenn)

```


```{r}

#read in data and clean

AAC_freq_filter.na <- read.csv(here("data/AAC_freq_filter.na.csv"))
GAAS_ <- read.csv(here("data/jsle_GAAS_with_metadata.csv"), row.names = 1)

demos <- read.csv(here("data/JSLE_combined_meta_treatment_updated24_.csv", na.strings=c("","NA")))
demos$Patient_ID <- as.character(demos$Patient_ID)
  demos <- demos %>%
  mutate(Ethnicity_def = ifelse(Ethnicity_def == "Any other Asian Background", "Other Asian", Ethnicity_def))
  

ethnicity_order <- c("Black African/Caribbean", "Caucasian", "East Asian", "South Asian", "Other Asian")

AAC_freq_filter.na <- AAC_freq_filter.na %>%
  mutate(Ethnicity_def = ifelse(Ethnicity_def == "Any other Asian Background", "Other Asian", Ethnicity_def))
GAAS_ <- GAAS_ %>%
  mutate(Ethnicity_def = ifelse(Ethnicity_def == "Any other Asian Background", "Other Asian", Ethnicity_def))

```



#Figure 1

```{r}

#venn

venn_list2 <- list(
  `GAAS only` = rownames(GAAS_),
  `AAC & GAAS`= AAC_freq_filter.na$Patient_ID
)


colors <- c("skyblue", "lightcoral")

# Create the Venn diagram
venn <- ggvenn(venn_list2, 
               fill_color = colors, 
               stroke_color = "black", 
               text_size = 20, 
               set_name_size = 20, show_percentage = FALSE, 
               auto_scale = TRUE) 
venn$layers[[3]]$data$x <- c(-0.7, 0.4)


demos_plots <- demos %>% filter(Tag == "include") %>%
  mutate(analysis_set = ifelse(Patient_ID %in% AAC_freq_filter.na$Patient_ID, "AAC & GAAS", NA))%>%
  mutate(analysis_set = ifelse(Patient_ID %in% rownames(GAAS_) & is.na(analysis_set), "GAAS only", analysis_set ))
demos_plots <- demos_plots %>% filter(!is.na(analysis_set))

demos_plots_aac <- demos_plots %>% filter(analysis_set == "AAC & GAAS")
median_age_aac <- median(demos_plots_aac$Diagnosis_Age, na.rm = TRUE)
median_age <- median(demos_plots$Diagnosis_Age, na.rm = TRUE)

p1 <- ggplot(demos_plots, aes(x = Diagnosis_Age)) +
  geom_histogram() +
  labs(x = "Diagnosis Age", y="Number of patients") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 50, angle = 45, hjust = 1) + scale_x_discrete(labels = function(x) str_wrap(x, width = 3))) +
  theme_bw(base_size = 50)  +
  geom_vline(aes(xintercept = median_age), linetype = "dotted", color = "black", size = 5)
p1

p2 <- ggplot(demos_plots, aes(x =factor(Ethnicity_def, levels = ethnicity_order))) +
  geom_bar() +
  labs(x = "Ethnicity", y="Number of patients") +
  theme_minimal() +
  theme(text = element_text(size = 50))+ scale_x_discrete(labels = function(x) str_wrap(x, width = 3)) +
  theme_bw(base_size = 50) 



plot1<-plot_grid(p1,p2, ncol=2, align='vh', vjust=1, scale = 1)
#plot1 <- ggdraw(add_sub(plot1, "Patients included in GAAS analysis", vpadding=grid::unit(0,"lines"), y=4, x= 0.5, vjust=-22, size = 50, fontface = "bold"))
plot1


plot_fin <- plot_grid(venn, plot1, ncol=1, labels="AUTO", label_size = 90, scale = 0.9) + theme(plot.background = element_rect(fill = "white"))

plot_fin


```



#Figure 2

```{r}
library(ggpubr)
p1 <- ggplot(AAC_freq_filter.na, aes(Diagnosis_Age, sum)) + geom_point(size=4) + geom_smooth(method='lm', formula= y~x, colour="black", size=3) +
  annotate("text", x=13.5, y=570, label= "R=-0.015, p=0.012", size=12 )
p1 <- p1 + labs(x ="Diagnosis Age", y = "Alternative Allele Counts") + theme_bw(base_size = 40)

p2 <- ggplot(AAC_freq_filter.na, aes(Diagnosis_Age, sum, group=factor(Ethnicity_def, levels = ethnicity_order), colour=factor(Ethnicity_def, levels = ethnicity_order))) + geom_point(size=4) + geom_smooth(method='lm', formula= y~x, size=3) 
p2 <- p2 + labs(x ="Diagnosis Age", y = "Alternative Allele Counts" , colour = "Ethnicity") + theme_bw(base_size = 40)


plot <- plot_grid(p1,p2, ncol = 2, rel_widths = c(0.7, 1), labels = "AUTO", label_size = 50)
plot


```


#Figure 3

```{r}

stat.test <- tibble::tribble(
  ~group1, ~group2,   ~p.adj, ~y.position,
    "Black African/Caribbean",     "Caucasian", "***", 585,
    "Black African/Caribbean",     "East Asian", "***",593,
      "Black African/Caribbean",     "South Asian", "***",601,
  "Black African/Caribbean",     "Other Asian", "***",609,
  "Caucasian",     "East Asian", "***", 525,
    "Caucasian",     "South Asian", "***",534,
      "Caucasian",     "Other Asian", "***",543
  )

p1 <-  ggplot(AAC_freq_filter.na, aes(factor(Ethnicity_def, levels = ethnicity_order), sum)) + geom_boxplot(aes(fill=Gender))
p1 <- p1 + theme_bw(base_size = 40) + labs(x ="Ethnicity", y = "Alternative Allele Counts" , colour = "Sex") + theme() +
scale_x_discrete(labels = function(x) str_wrap(x, width = 5)) + stat_pvalue_manual(
    stat.test,
    label = "p.adj", size = 14
    )

p1


### preprocessing to get d1 in gene level analyses script

d1 <- d1 %>%
 mutate(Ethnicity_def = ifelse(Ethnicity_def == "Any other Asian Background", "Other Asian", Ethnicity_def))

d1 <- na.omit(d1)
#patient has no ethnicity data, but isn't being flagged as NA
d1 <- d1[d1$Patient_ID != "15122", ]
#d1 <- d1[-150,]
p2 <- ggplot(d1, aes(PC1, PC2, colour = factor(Ethnicity_def, levels = ethnicity_order), id = Patient_ID, label = Patient_ID)) +
  geom_point(size = 7) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) +
  theme_bw(base_size = 40) +
  theme(axis.title=element_text(face="bold")) + stat_ellipse(data = d1[d1$Ethnicity_def == "Black African/Caribbean", ], 
               aes(x = PC1, y = PC2, color = Ethnicity_def, group = Ethnicity_def), 
               level = 0.95) +
  labs(colour = "Ethnicity")
p2 <- p2 + labs(colour = "Ethnicity")

p2



plot <- plot_grid(p1,p2, ncol = 2, rel_widths = c(0.9, 1), 
                  labels = "AUTO", label_size = 50)
plot


```





#figure 5


```{r}

p1 <-  ggplot(GAAS_, aes(x=factor(Neuropsychiatric2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), ACP5)) + geom_boxplot(outlier.size = 3)
p1 <- p1 + labs(x ="Neuropsychiatric Severity", y = expression(paste(italic("ACP5"), " count"))) +
theme_bw(base_size = 40, ) + ggtitle(expression(italic("ACP5"))) +
theme(plot.title = element_text(face="italic"))
p1

p2 <-  ggplot(GAAS_, aes(x=factor(Neuropsychiatric2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), RASGRP3)) + geom_boxplot(outlier.size = 3)
p2 <- p2 + labs(x ="Neuropsychiatric Severity", y = expression(paste(italic("RASGRP3"), " count"))) +
theme_bw(base_size = 40, ) + ggtitle(expression(italic("RASGRP3"))) +
theme(plot.title = element_text(face="italic"))


p3 <-  ggplot(GAAS_, aes(x=factor(Neuropsychiatric2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), RNASEH2A)) + geom_boxplot(outlier.size = 3)
p3 <- p3 + labs(x ="Neuropsychiatric Severity", y = expression(paste(italic("RNASEH2A"), " count"))) +
theme_bw(base_size = 40, ) + ggtitle(expression(italic("RNASEH2A"))) +
theme(plot.title = element_text(face="italic"))


p4 <-  ggplot(GAAS_, aes(x=factor(Neuropsychiatric2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), TYK2)) + geom_boxplot(outlier.size = 3)
p4 <- p4 + labs(x ="Neuropsychiatric Severity", y = expression(paste(italic("TYK2"), " count"))) +
theme_bw(base_size = 40, ) + ggtitle(expression(italic("TYK2"))) +
theme(plot.title = element_text(face="italic"))



plot <- plot_grid(p1,p2,p3,p4, ncol = 2)
plot


p1 <-  ggplot(GAAS_, aes(x=factor(Renal2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), ACP5)) + geom_boxplot(outlier.size = 3)
p1 <- p1 + labs(x ="Renal Severity",  y = expression(paste(italic("ACP5 count")))) +
theme_bw(base_size = 40, ) + ggtitle("ACP5") +
theme(plot.title = element_text(face="italic"))
p1
p2 <-  ggplot(GAAS_, aes(x=factor(Renal2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), ITGAM)) + geom_boxplot(outlier.size = 3)
p2 <- p2 + labs(x ="Renal Severity",y = expression(paste(italic("ITGAM count")))) +
theme_bw(base_size = 40, ) + ggtitle("ITGAM") +
theme(plot.title = element_text(face="italic"))
p2
p3 <- p3 + labs(x ="Renal Severity", y = "LYN count") +
theme_bw(base_size = 40, ) + ggtitle("LYN") +
theme(plot.title = element_text(face="italic"))
p3
p4 <-  ggplot(GAAS_, aes(x=factor(Renal2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), TNFAIP3)) + geom_boxplot(outlier.size = 3)
p4 <- p4 + labs(x ="Renal Severity", y = expression(paste(italic("TNFAIP3 count")))) +
theme_bw(base_size = 40, ) + ggtitle("TNFAIP3") +
theme(plot.title = element_text(face="italic"))
p4
plot2 <- plot_grid(p1,p2,p3,p4, ncol = 2)


plot_3 <-  plot_grid(plot, plot2, ncol = 2, labels = "AUTO", label_size = 70)

plot_3
plot_3 <-  plot_grid(plot, plot2, ncol = 1, labels = "AUTO", label_size = 70)
plot_3


```



#figure 6

```{r}

#jsle_combned <- jsle_combned %>%
 # mutate(Treament_Group = ifelse(Treament_Group == "Aggressive", "Intensive", "Non-intensive"))


AAC_freq_filter.na <- AAC_freq_filter.na %>%
 mutate(Treament_Group = ifelse(Treament_Group == "Aggressive", "Intensive", "Non-intensive"))



p11 <-  ggplot(GAAS_, aes(x=factor(Treament_Group), ACP5)) + geom_boxplot()
p11 <- p11 + labs(x ="Treatment Group", y = expression(paste(italic("ACP5"), " count"))) +
theme_bw(base_size = 50, ) + ggtitle(expression(italic("ACP5"))) +
theme(plot.title = element_text(face="italic"))


p12 <-  ggplot(GAAS_, aes(x=factor(Treament_Group), ITGAM)) + geom_boxplot()
p12 <- p12 + labs(x ="Treatment Group", y = expression(paste(italic("LYN"), " count"))) +
theme_bw(base_size = 50, ) + ggtitle(expression(italic("LYN"))) +
theme(plot.title = element_text(face="italic"))


p13 <-  ggplot(GAAS_, aes(x=factor(Treament_Group), PXK)) + geom_boxplot()
p13 <- p13 + labs(x ="Treatment Group", y = expression(paste(italic("PXK"), " count"))) +
theme_bw(base_size = 50, ) + ggtitle(expression(italic("PXK"))) +
theme(plot.title = element_text(face="italic"))


p14 <-  ggplot(GAAS_, aes(x=factor(Treament_Group), RNASEH2A)) + geom_boxplot()
p14 <- p14 + labs(x ="Treatment Group", y = expression(paste(italic("RNASEH2A"), " count"))) +
theme_bw(base_size = 50, ) + ggtitle(expression(italic("RNASEH2A"))) +
theme(plot.title = element_text(face="italic"))



plot <- plot_grid(p11,p12,p13,p14, ncol = 2)


stat.test <- tibble::tribble(
  ~group1, ~group2,   ~p.adj,
    "Intensive",     "Non-intensive", "***"
  )


p1 <-  ggplot(AAC_freq_filter.na, aes(Treament_Group, sum)) + geom_boxplot()
p1 <- p1 + theme_bw(base_size = 60) + labs(x ="Treatment Group", y = "Alternative Allele Counts") + theme(text = element_text(size = 50))+ scale_x_discrete(labels = function(x) str_wrap(x, width = 5)) + stat_pvalue_manual(
    stat.test, 
    y.position = 610, step.increase = 0.075,
    label = "p.adj", size = 18
    )


stat.test <- tibble::tribble(
  ~Ethnicity_def, ~group1, ~group2,   ~p.adj, ~y.position,
  "Black African/Caribbean","Aggressive",     "Standard", "*", 584
  )


p2 <- ggplot(AAC_freq_filter.na, aes(x = factor(Ethnicity_def, levels = ethnicity_order), y = sum)) + 
  geom_boxplot(aes(fill = Treament_Group)) + 
  stat_pvalue_manual(stat.test, 
                     label = "p.adj", 
                     x = "Ethnicity_def",
                     size = 20)

p2 <- p2 +
theme_bw(base_size = 60) +
labs(x = "Ethnicity", y = "Alternative Allele Counts", colour = "Treatment Group", fill="Treatment Group") +
theme(text = element_text(size = 50), 
legend.position = "bottom",  legend.direction = "vertical") + scale_x_discrete(labels = function(x) str_wrap(x, width = 2))

top_row <- plot_grid(p1,p2, ncol=2, labels="AUTO", label_size = 70, align = "h", axis="bt")


plot2 <- plot_grid(top_row, plot, labels=c("", "C"), label_size = 70, ncol = 1,  align = "h", axis="lr")



```



## Supplementary figures


#figure1

```{r}
library(ggpubr)


p1 <- ggscatter(AAC_freq_filter.na, x = "SLEDAI_highest", y = "sum",
add = "reg.line", conf.int = TRUE,
cor.coef = TRUE, cor.method = "pearson",cor.coef.size = 10,
xlab = "Highest SLEDAI score", ylab = "Alternative Allele Counts") +
theme_classic(base_size = 30)


p2 <- ggscatter(AAC_freq_filter.na, x = "BILAG_highest", y = "sum",
add = "reg.line", conf.int = TRUE,
cor.coef = TRUE, cor.method = "pearson",cor.coef.size = 10,
xlab = "Highest pBILAG score", ylab = "Alternative Allele Counts")  +
theme_classic(base_size = 30)


p3 <- ggscatter(AAC_freq_filter.na, x = "SLICC_last", y = "sum",
add = "reg.line", conf.int = TRUE,
cor.coef = TRUE, cor.method = "pearson",cor.coef.size = 10,
xlab = "SLICC/ACR Damage Index", ylab = "Alternative Allele Counts") +
theme_classic(base_size = 30)


plot <- plot_grid(p1,p2,p3, ncol =1, labels="AUTO", label_size = 50)

```



#figure2
```{r}
p1 <-  ggplot(GAAS_, aes(x=factor(Haematological2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), ACP5)) + geom_boxplot()
p1 <- p1 + labs(x = "", y = expression(paste(italic("ACP5"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))

p2 <-  ggplot(GAAS_, aes(x=factor(Haematological2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), DNASE1)) + geom_boxplot()
p2 <- p2 + labs(x = "", y = expression(paste(italic("DNASE1"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))

p3 <-  ggplot(GAAS_, aes(x=factor(Haematological2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), RNASEH2A)) + geom_boxplot()
p3 <- p3 + labs(x = "", y = expression(paste(italic("RNASEH2A"), " count"))) +
theme_bw(base_size = 60 ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))

p4 <-  ggplot(GAAS_, aes(x=factor(Haematological2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), UBE2L3)) + geom_boxplot()
p4 <- p4 + labs(x = "", y = expression(paste(italic("UBE2L3"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 12, hjust=0.5))


plot<-plot_grid(p1, p2,p3,p4, ncol=4, align='vh', vjust=1, scale = 1)
plot <- ggdraw(add_sub(plot, "Haematological severity", vpadding=grid::unit(0,"lines"),y=6, x=0.5, vjust=-22, size = 50,  fontface = "bold"))


p1 <-  ggplot(GAAS_, aes(x=factor(Cardiorespiratory2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), IRF8)) + geom_boxplot()
p1 <- p1 + labs(x = "", y = expression(paste(italic("IRF8"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))

p2 <-  ggplot(GAAS_, aes(x=factor(Cardiorespiratory2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), ITGAM)) + geom_boxplot()
p2 <- p2 + labs(x = "", y = expression(paste(italic("ITGAM"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))

p3 <-  ggplot(GAAS_, aes(x=factor(Cardiorespiratory2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), UBE2L3)) + geom_boxplot()
p3 <- p3 + labs(x = "", y = expression(paste(italic("UBE2L3"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))


plot2<-plot_grid(p1, p2,p3, ncol=3, align='vh', vjust=1, scale = 1)
plot2 <- ggdraw(add_sub(plot2, "Cardiorespiratory severity", vpadding=grid::unit(0,"lines"),y=6, x=0.5, vjust=-22, size = 50, fontface = "bold"))



p1 <-  ggplot(GAAS_, aes(x=factor(Gastrointestinal2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), ITGAM)) + geom_boxplot()
p1 <- p1 + labs(x = "", y = expression(paste(italic("ITGAM"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))

p2 <-  ggplot(GAAS_, aes(x=factor(Gastrointestinal2004_severity, level=c('Never', 'Mild', 'Moderate', 'Severe')), PXK)) + geom_boxplot()
p2 <- p2 + labs(x = "", y = expression(paste(italic("PXK"), " count"))) +
theme_bw(base_size = 60, ) +
theme(plot.title = element_text(face="italic"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))

plot3<-plot_grid(p1,p2, ncol=2, align='vh', vjust=1, scale = 1)
plot3 <- ggdraw(add_sub(plot3, "Gastrointestinal severity", vpadding=grid::unit(0,"lines"),y=6, x= 0.5, vjust=-22, size = 50, fontface = "bold"))


plot_fin <- plot_grid(plot,plot2,plot3, ncol=1, labels="AUTO", label_size = 80)
plot_fin

```

